version: "3"
services:
    # frontend:
    #     depends_on:
    #         - certbot
    #         - nginx
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile.dev.2
    #     volumes:
    #         - ./frontend/src:/app/src
    #         - ./frontend/content:/app/content
    #     ports:
    #         - "8000:8000"
    #         - "9929:9929"
    #         - "9230:9230"
    nginx:
        image: nginx:1.15-alpine
        restart: unless-stopped
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

